CORPUS = [
    "The morning fog rolled slowly across the quiet valley.",
    "She poured a cup of strong black coffee before sunrise.",
    "The old wooden bridge creaked under the weight of the cart.",
    "Scientists discovered a new species of frog in the rainforest.",
    "He tightened the last bolt and started the rumbling engine.",
    "The children laughed as the puppy chased its own tail.",
    "A cold wind swept through the empty city streets at midnight.",
    "The chef sprinkled fresh basil over the steaming pasta.",
    "Investors watched nervously as the stock market tumbled.",
    "The astronaut floated gently toward the docking station.",
    "On Monday the committee will vote on the new proposal.",
    "The violinist closed her eyes during the final movement.",
    "Heavy rain flooded the narrow roads near the river.",
    "The programmer fixed the bug after hours of careful debugging.",
    "Ancient ruins lay buried beneath the desert sand for centuries.",
    "The toddler stacked the colorful blocks into a wobbly tower.",
    "A flock of geese flew south as winter approached.",
    "The detective examined the muddy footprints by the door.",
    "They hiked for miles before reaching the snowy summit.",
    "The bakery smelled of warm bread and cinnamon rolls.",
    "The lawyer presented the final argument to the jury.",
    "Lightning split the sky above the trembling forest.",
    "She typed the password and the screen flickered to life.",
    "The farmer planted rows of corn under the blazing sun.",
    "A gentle melody drifted from the open window upstairs.",
    "The submarine descended into the dark crushing depths.",
    "He counted thirty-seven coins scattered across the table.",
    "The museum displayed paintings from the seventeenth century.",
    "Volunteers cleaned the beach and collected bags of plastic.",
    "The cat curled up beside the warm crackling fireplace.",
    "Traffic crawled along the highway during the evening rush.",
    "The surgeon studied the X-ray under the bright lamp.",
    "Tourists photographed the towering cathedral at noon.",
    "The river carved a deep canyon over millions of years.",
    "A nervous student forgot the answer during the exam.",
    "The blacksmith hammered the glowing iron into shape.",
    "Snowflakes settled silently on the frozen pond.",
    "The journalist interviewed the mayor about the budget.",
    "Bees buzzed lazily among the blooming lavender fields.",
    "The pilot announced a short delay before takeoff.",
    "He whispered the secret and she gasped in surprise.",
    "The library was silent except for the turning pages.",
    "A rainbow arched over the green rolling hills.",
    "The mechanic replaced the worn brakes on the truck.",
    "Dancers twirled across the polished ballroom floor.",
    "The volcano erupted, sending ash high into the air.",
    "She wrapped the gift in shiny silver paper.",
    "The fishermen hauled the heavy nets onto the deck.",
    "A spider spun its web between two rusty fence posts.",
    "The teacher explained the equation on the chalkboard.",
    "Waves crashed against the jagged rocks below the cliff.",
    "The puppy buried the bone in the soft garden soil.",
    "Engineers tested the rocket before the historic launch.",
    "The crowd cheered as the runner crossed the finish line.",
    "He sketched the mountains while sitting on a wooden bench.",
    "The nurse checked the patient's pulse every hour.",
    "Autumn leaves drifted down onto the quiet path.",
    "The hacker tried every combination but the vault stayed locked.",
    "A whale surfaced and sprayed mist into the salty air.",
    "The carpenter measured the plank twice before cutting.",
    "Thunder rumbled in the distance as the clouds gathered.",
    "The queen waved to the cheering crowd from the balcony.",
    "They roasted marshmallows over the flickering campfire.",
    "The clock struck midnight and the lights went out.",
    "A curious fox peered out from behind the hedge.",
    "The pianist practiced the same passage again and again.",
    "Sailors spotted land after many weeks at sea.",
    "The chemist mixed the two liquids and they turned blue.",
    "He parked the bicycle against the old brick wall.",
    "The owl hunted silently through the moonlit woods.",
    "The startup raised millions from eager investors.",
    "She knitted a warm scarf for her grandfather.",
    "The earthquake shook the buildings for several seconds.",
    "A beam of sunlight broke through the heavy clouds.",
    "The waiter recommended the grilled salmon with lemon.",
    "Children built a sandcastle near the gentle waves.",
    "The soldier saluted and marched through the gate.",
    "The gardener trimmed the roses along the stone path.",
    "A meteor streaked brightly across the night sky.",
    "The barista drew a leaf in the foam of the latte.",
    "The professor lectured on the history of ancient Rome.",
    "Rain tapped softly against the bedroom window.",
    "The dog barked loudly at the passing mail carrier.",
    "They celebrated the victory with fireworks and music.",
    "The locksmith picked the rusty lock in seconds.",
    "A butterfly landed on the bright yellow sunflower.",
    "The captain steered the ship through the narrow strait.",
    "She solved the puzzle just before the timer ran out.",
    "The miners dug deep into the dark mountain tunnel.",
    "Frost coated the grass on the first cold morning.",
    "The orchestra tuned their instruments before the concert.",
    "He read the map carefully and chose the shorter route.",
    "The kitten pounced on the rolling ball of yarn.",
    "Workers poured concrete for the new bridge foundation.",
    "The wizard muttered a spell and the candle flickered.",
    "A train whistle echoed through the sleepy town.",
    "The diver explored the colorful coral reef below.",
    "She painted the fence a cheerful shade of blue.",
    "The crowd fell silent as the magician raised his hand.",
    "Geologists collected rock samples from the crater.",
    "The baby giggled at the bright spinning mobile.",
    "He brewed a pot of green tea and sat by the window.",
    "The storm knocked out power across the entire region.",
    "A herd of elephants crossed the dusty savanna.",
    "The editor corrected the typos in the morning edition.",
    "Climbers anchored their ropes to the icy ledge.",
    "The shopkeeper counted the day's earnings carefully.",
    "Fireflies blinked across the meadow after dusk.",
    "The robot vacuumed the living room while they slept.",
    "She hummed a tune while watering the potted plants.",
    "The jury deliberated for three long days.",
    "A gentle current carried the canoe downstream.",
    "The baker frosted the cake with smooth white icing.",
    "Soldiers built a bridge across the rushing river.",
    "The comet will not return for another seventy years.",
    "He plugged in the guitar and strummed the first chord.",
    "The nurse wheeled the cart down the quiet corridor.",
    "Ducks paddled across the calm green pond.",
    "The scientist recorded the temperature every ten minutes.",
    "A warm breeze rustled the palm trees on the shore.",
    "The meeting is scheduled for Tuesday at nine in the morning.",
    "In January the lake freezes over and the skaters arrive.",
    "The function returns zero when the input list is empty.",
    "She bought three apples, two oranges, and a loaf of bread.",
    "The temperature dropped to minus ten degrees overnight.",
    "He saved the file and pushed the changes to the server.",
    "The recipe calls for two cups of flour and one egg.",
    "On Friday the band will play at the downtown theater.",
    "The password must contain at least eight characters.",
    "By December the streets were covered in glittering lights.",
]
